import control_problems_involving_ordinary_differential_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace control_problems_involving_ordinary_differential_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end control_problems_involving_ordinary_differential_lemma_canonical_lane_mathlib
end HautevilleHouse
